[Interface]
Address = 10.8.0.1/24
ListenPort = 51820
PrivateKey = 4JNtd5sZDzRXDZGx5cR66d5tnLDsDH+N++STnTFqc3g=
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

# Peers will be added here dynamically
